import { PrismaClient } from "@prisma/client";
import { subDays } from "date-fns";

const prisma = new PrismaClient();
const now = new Date();

const complaints = [
  {
    transport: "Train",
    issueType: "Overcrowding",
    vehicleNo: "WR-4567",
    location: "Churchgate Station",
    dateOfIncident: subDays(now, 5),
    description: "Extreme overcrowding in evening local train",
    mediaFiles: [{ url: "https://example.com/train-crowd.jpg", publicId: "train-crowd1" }],
    isAnonymous: false,
    contactName: "Zaid Shaikh",
    contactEmail: "zaidshaikh2811@gmail.com",
    status: "in_progress",
    submittedAt: subDays(now, 5),
    inProgressAt: subDays(now, 4),
    resolvedAt: null,
  },
  {
    transport: "Bus",
    issueType: "FaultyAC",
    vehicleNo: "MH12AB1234",
    location: "Pune Station",
    dateOfIncident: subDays(now, 15),
    description: "Bus AC not working during summer heat",
    mediaFiles: [],
    isAnonymous: true,
    contactName: "Anonymous",
    contactEmail: "Anonymous",
    status: "resolved",
    submittedAt: subDays(now, 15),
    inProgressAt: subDays(now, 14),
    resolvedAt: subDays(now, 10),
  },
  {
    transport: "Metro",
    issueType: "busdelay",
    vehicleNo: "MUM-METRO-22",
    location: "Andheri Metro Station",
    dateOfIncident: subDays(now, 25),
    description: "Metro delayed by 25 minutes without announcements",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Aisha Khan",
    contactEmail: "aisha@example.com",
    status: "resolved",
    submittedAt: subDays(now, 25),
    inProgressAt: subDays(now, 24),
    resolvedAt: subDays(now, 22),
  },
  {
    transport: "Train",
    issueType: "RudeStaff",
    vehicleNo: "CR-1123",
    location: "Dadar Station",
    dateOfIncident: subDays(now, 35),
    description: "Ticket counter staff behaved rudely with passengers",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Ravi Verma",
    contactEmail: "ravi@example.com",
    status: "pending",
    submittedAt: subDays(now, 35),
    inProgressAt: null,
    resolvedAt: null,
  },
  {
    transport: "Bus",
    issueType: "UncleanVehicle",
    vehicleNo: "MH14XY9876",
    location: "Swargate Depot",
    dateOfIncident: subDays(now, 45),
    description: "Bus seats and floor dirty, not cleaned for days",
    mediaFiles: [],
    isAnonymous: true,
    contactName: "Anonymous",
    contactEmail: "Anonymous",
    status: "in_progress",
    submittedAt: subDays(now, 45),
    inProgressAt: subDays(now, 44),
    resolvedAt: null,
  },
  {
    transport: "Other",
    issueType: "Other",
    vehicleNo: "AUTO-7788",
    location: "Bandra East",
    dateOfIncident: subDays(now, 55),
    description: "Auto rickshaw refused to go by meter",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Sana Sheikh",
    contactEmail: "sana@example.com",
    status: "resolved",
    submittedAt: subDays(now, 55),
    inProgressAt: subDays(now, 54),
    resolvedAt: subDays(now, 52),
  },
  {
    transport: "Train",
    issueType: "busdelay",
    vehicleNo: "WR-6677",
    location: "Borivali",
    dateOfIncident: subDays(now, 65),
    description: "Train delayed due to signaling issue",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Amit Desai",
    contactEmail: "amit@example.com",
    status: "resolved",
    submittedAt: subDays(now, 65),
    inProgressAt: subDays(now, 64),
    resolvedAt: subDays(now, 62),
  },
  {
    transport: "Bus",
    issueType: "RudeStaff",
    vehicleNo: "MH09ZZ4521",
    location: "Nashik Road",
    dateOfIncident: subDays(now, 75),
    description: "Conductor shouted at elderly passengers",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Priya Singh",
    contactEmail: "priya@example.com",
    status: "in_progress",
    submittedAt: subDays(now, 75),
    inProgressAt: subDays(now, 74),
    resolvedAt: null,
  },
  {
    transport: "Metro",
    issueType: "UncleanVehicle",
    vehicleNo: "MUM-METRO-12",
    location: "Versova",
    dateOfIncident: subDays(now, 85),
    description: "Dirty coach floor and uncollected garbage",
    mediaFiles: [],
    isAnonymous: true,
    contactName: "Anonymous",
    contactEmail: "Anonymous",
    status: "pending",
    submittedAt: subDays(now, 85),
    inProgressAt: null,
    resolvedAt: null,
  },
  {
    transport: "Train",
    issueType: "FaultyAC",
    vehicleNo: "CR-2222",
    location: "Thane",
    dateOfIncident: subDays(now, 88),
    description: "AC compartment blower not working properly",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Rohit Sharma",
    contactEmail: "rohit@example.com",
    status: "resolved",
    submittedAt: subDays(now, 88),
    inProgressAt: subDays(now, 87),
    resolvedAt: subDays(now, 85),
  },
  {
    transport: "Bus",
    issueType: "Other",
    vehicleNo: "MH13LM3322",
    location: "Kolhapur",
    dateOfIncident: subDays(now, 80),
    description: "Bus late by more than 1 hour without notice",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Vikas Patil",
    contactEmail: "vikas@example.com",
    status: "resolved",
    submittedAt: subDays(now, 80),
    inProgressAt: subDays(now, 79),
    resolvedAt: subDays(now, 77),
  },
  {
    transport: "Metro",
    issueType: "RudeStaff",
    vehicleNo: "MUM-METRO-88",
    location: "Ghatkopar",
    dateOfIncident: subDays(now, 70),
    description: "Security staff misbehaved with passengers",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Neha Gupta",
    contactEmail: "neha@example.com",
    status: "pending",
    submittedAt: subDays(now, 70),
    inProgressAt: null,
    resolvedAt: null,
  },
  {
    transport: "Other",
    issueType: "Other",
    vehicleNo: "TAXI-5566",
    location: "Powai",
    dateOfIncident: subDays(now, 60),
    description: "Taxi driver refused to take digital payment",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Irfan Khan",
    contactEmail: "irfan@example.com",
    status: "resolved",
    submittedAt: subDays(now, 60),
    inProgressAt: subDays(now, 59),
    resolvedAt: subDays(now, 57),
  },
  {
    transport: "Bus",
    issueType: "FaultyAC",
    vehicleNo: "MH12-AB-1122",
    location: "Shivajinagar Depot",
    dateOfIncident: subDays(now, 50),
    description: "AC was not working during a hot afternoon.",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Rohit Patil",
    contactEmail: "rohit@example.com",
    status: "resolved",
    submittedAt: subDays(now, 50),
    inProgressAt: subDays(now, 49),
    resolvedAt: subDays(now, 47),
  },
  {
    transport: "Train",
    issueType: "busdelay",
    vehicleNo: "WR-8901",
    location: "Borivali Station",
    dateOfIncident: subDays(now, 40),
    description: "Train delayed by 40 minutes without announcements.",
    mediaFiles: [],
    isAnonymous: true,
    contactName: "Anonymous",
    contactEmail: "Anonymous",
    status: "resolved",
    submittedAt: subDays(now, 40),
    inProgressAt: subDays(now, 39),
    resolvedAt: subDays(now, 37),
  },
  {
    transport: "Metro",
    issueType: "Other",
    vehicleNo: "Line1-Gateway",
    location: "Ghatkopar Station",
    dateOfIncident: subDays(now, 30),
    description: "Ticket machine not accepting UPI payments.",
    mediaFiles: [],
    isAnonymous: false,
    contactName: "Sneha Desai",
    contactEmail: "sneha@example.com",
    status: "in_progress",
    submittedAt: subDays(now, 30),
    inProgressAt: subDays(now, 29),
    resolvedAt: null,
  },
  // Continue similar pattern for remaining complaints up to 90 days…
];

async function main() {
  console.log("🌱 Seeding complaints...");

  for (const complaint of complaints) {
    await prisma.complaint.create({
      data: {
        ...complaint,
        user: { connect: { id: 1 } }, // all complaints linked to userId=1
      },
    });
  }

  console.log("✅ Complaints seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });